### ISSUE TITLE
After enabling HPOS the manifest page loads really slow

### ISSUE THREAD

**Issue by mpts87** [ItellaPlugins/itella-shipping-woocommerce#100]
After enabling "High-performance order storage (recommended)" the manifest page loads really slow, with "WordPress posts storage (legacy)" everything works fine.

Page affected: https://domain-name/wp-admin/admin.php?page=itella-manifest

Query monitor reports 2 slow queries, file attached.
[query-monitor-itella.txt](https://github.com/ItellaPlugins/itella-shipping-woocommerce/files/14294302/query-monitor-itella.txt)

Is it woocommerce or itella-shipping-woocommerce plugin problem?

**Comment by markakk** [comment]
Hello,

This problem fixed in PR #110. We recommend waiting for a new version of the plugin to be released.
