### ISSUE TITLE
Useless and confusing settings

### ISSUE THREAD

**Issue by alekln** [ItellaPlugins/itella-shipping-woocommerce#44]
i was able to find part of useless code 
`'api_user_2711' => array(
            'title' => __('API user (Product 2711)', 'itella-shipping'),
            'type' => 'text',
        ),
        'api_pass_2711' => array(
            'title' => __('Api password (Product 2711)', 'itella-shipping'),
            'type' => 'text',
        ),
        'api_contract_2711' => array(
            'title' => __('Api contract number (Product 2711)', 'itella-shipping'),
            'type' => 'text',
        ),`

this adds extra settings fields on plugin configuration but in result during parcel request system fails with alert that client not authenticated, and reason that it uses "api_user_2317" instead of "api_user_2711". Please validate and clean if it is needed

**Comment by markakk** [comment]
Please contact Smartpost Itella for this problem. We will only be able to check this problem after receiving it from Smartpost.
