### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by mpts87** [ItellaPlugins/itella-shipping-woocommerce#64]
1. It would be great if users with Shop Manager user roles could register and print shipping labels.
2. Ability to delete order shipments from the Smartpost shipments New orders table.

Thank you for a good plugin.

**Comment by markakk** [comment]
Hello,

1. Added display of "Smartpost shipments" page for "Shop manager" user role for next update (PR: #59).
2. It is not possible to delete orders. Orders in the "New orders" tab can be moved to the "Completed orders" tab by creating a manifest for them.
