### ISSUE TITLE
Shipment registration 500 error

### ISSUE THREAD

**Issue by tyyoyy** [ItellaPlugins/itella-shipping-woocommerce#68]
On this page /wp-admin/admin.php?page=itella-manifest
If I register shipments for some orders, I get 500 error. 

Error: 500, Max weight allowed for shipment via Parcel Connect service is 31.5 kg!
On the order page, the weight is marked: 200g (shows as 200.000)

If I change the order weight manually to 1g (shows 1.000) then it works, I can register the shipment. I think you have an issue with measurements.

**Comment by markakk** [comment]
Hello,

The problem you described is fixed in version 1.3.7 of the plugin. We checked that everything works fine in the latest version of the plugin.
