### ISSUE TITLE
Fatal error when viewing itella manifest page and there is an order that contains a product that is deleted from database.

### ISSUE THREAD

**Issue by mpts87** [ItellaPlugins/itella-shipping-woocommerce#81]
Fatal error: Uncaught Error: Call to a member function get_weight() on bool in /staging/wp-content/plugins/itella-shipping-woocommerce-master/includes/class-itella-shipping-wc.php:161 

Stack trace: 

#0 /staging/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-manifest-page.php(727): Itella_Shipping_Wc->get_order_items(Object(Automattic\WooCommerce\Admin\Overrides\Order)) 
#1 /staging/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-manifest-page.php(534): Itella_Manifest::get_shipping_parameters(84521) 
#2 /staging/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-manifest-page.php(103): Itella_Manifest::load_manifest_page() 
#3 /staging/wp-includes/class-wp-hook.php(308): itella_manifest_page('') 
#4 /staging/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) 
#5 /staging/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#6 /staging/wp-admin/admin.php(259): do_action('woocommerce_pag...') 
#7 {main} thrown in /staging/wp-content/plugins/itella-shipping-woocommerce-master/includes/class-itella-shipping-wc.php on line 161

**Comment by markakk** [comment]
Hello,

Problem fixed in plugin version 1.4.2
