### ISSUE TITLE
LT parcel locker error

### ISSUE THREAD

**Issue by mpts87** [ItellaPlugins/itella-shipping-woocommerce#87]
Error: 400, {"shipment.consignment.additionalservice":["Additional service Pickup point (2106) does not belong to the product Parcel Connect (2711)."]}

For example: KLAIPĖDA, Smartpost BIG Klaipėda, Taikos pr. 141, Klaipėda, 94284

**Comment by markakk** [comment]
Hello,

This error was temporary on the Itella server side.
