### ISSUE TITLE
validatePhone function error

### ISSUE THREAD

**Issue by AleksFad** [ItellaPlugins/itella-shipping-woocommerce#88]
It is impossible to Register shipment with Estonian phone to Finland address.
Error: "Invalid phone number supplied for FI country. Tested phone number: +372...."

Preconditions (*)
Version:  v1.3.7
Also reproducible on fresh version (v1.4.2)

Steps to reproduce (*)
Make order with EE phone using FI address

Expected result (*)
On "Register shipment" order is forwarded

Actual result (*)
Error: "Invalid phone number supplied for FI country. Tested phone number: +372...."

For now i commented out 
libs/itella-api/src/Shipment/Party.php 
validatePhone() function preg_match if

**Comment by markakk** [comment]
Hello,

As we know, the recipient's phone number must match the recipient's country. If the shipment is sent to Finland, the recipient's phone number must be Finnish.

**Comment by skyzer** [comment]
I have same issue, all combinations of phone numbers were entered by users: +3725 or without +372, and still. Looking at the code does not see anything right away what could be the issue as this needs debugging.
![image](https://github.com/ItellaPlugins/itella-shipping-woocommerce/assets/1395042/767a82bd-b3df-402c-9bba-38e6e8dcbdf5)

**Comment by markakk** [comment]
Hello @skyzer,

The regex should pass when the phone number starts with +3725.
The international code (+372) is required, so the phone number will not be allowed without it.
