### ISSUE TITLE
This plugin makes website load 15 seconds when logged in as admin

### ISSUE THREAD

**Issue by skyzer** [ItellaPlugins/itella-shipping-woocommerce#89]
Without this plugin activated loads 0.5 seconds, everything loads at least 10 seconds when I'm logged in.
Using Query Monitor to track it. See Query Monitor output. Nothing visibly eyecatching that cause problems.

Plugin deactivated:
<img width="1509" alt="image" src="https://github.com/ItellaPlugins/itella-shipping-woocommerce/assets/1395042/b4f74560-a65d-417b-b1f7-7c0dc793f37f">

With plugin activated
<img width="1412" alt="image" src="https://github.com/ItellaPlugins/itella-shipping-woocommerce/assets/1395042/3a6fb140-d1c5-48ef-bb28-0d203170818b">

I am getting some PHP warnings on deprecated issues
<img width="1342" alt="image" src="https://github.com/ItellaPlugins/itella-shipping-woocommerce/assets/1395042/354bf08c-e84f-490e-92a5-026089f59947">

Environment (PHP 8.2.12):
<img width="1240" alt="image" src="https://github.com/ItellaPlugins/itella-shipping-woocommerce/assets/1395042/a7b8b765-ff2b-438b-8920-9918542751cf">

**Comment by skyzer** [comment]
I found it. During `wp_after_admin_bar_render()` hook, there's a huge JSON file being downloaded 
`$itella_pickup_points_obj = new PickupPoints('https://delivery.plugins.itella.com/api/locations');`
https://github.com/ItellaPlugins/itella-shipping-woocommerce/blob/7ed17489e5c9ef7819d40161eed46a4f94cdff8e/admin/class-itella-shipping-method.php#L199C51-L199C100

So it's optimization issue up to devs.

**Comment by skyzer** [comment]
Hint: Issue is in `admin/class-itella-shipping-method.php` file on `update_locations()` function that pulls the huge JSON file `new PickupPoints('https://delivery.plugins.itella.com/api/locations');` and for some reason filesystem cache approach does not work nor even added wordpress's built in transient DB cache layer

**Comment by skyzer** [comment]
Proposed fix
https://github.com/ItellaPlugins/itella-shipping-woocommerce/pull/90

**Comment by markakk** [comment]
Hello,

Thank you for reporting the issue you noticed. The fix you suggested didn't acceptable for us, but we built a fix based on it in PR #91.
